add hypercore support
karissa/hyperhealth pull request #4
Opened 2016-12-22 15:58 UTC by yoshuawuyts

Add support for hypercores, closes GH-2

2016-12-22 16:42 UTC, joehand commented on index.js
>    archive.open(function () {
Should this be feed.open? Not sure that'd work on archives if content isn't defined yet though.

2016-12-22 16:42 UTC, joehand commented on index.js
> +  var feed = (archive.content) ? archive.content : archive
`archive.content` may be undefined here even though its an archive (if the `createArchive` function was used).

2016-12-22 16:42 UTC, joehand commented on index.js
>    var archive = archiveOrKey.key ? archiveOrKey : createArchive(archiveOrKey)
It'd be nice if you could pass in a hypercore key too, instead of just the feed.

2016-12-22 16:47 UTC, joehand requested changes
This isn't working with the CLI library anymore running `hyperhealth <key>` throws an error:

```
    for (var i = 0; i < feed.peers.length; i++) {
                                  ^

TypeError: Cannot read property 'length' of undefined
    at Object.get (/Users/joe/node_modules/hyperhealth/index.js:20:35)
```

2016-12-22 16:49 UTC, yoshuawuyts commented on index.js
>    var archive = archiveOrKey.key ? archiveOrKey : createArchive(archiveOrKey)
not sure how to detect if something is a hypercore or not based on a key - suggestions?

2016-12-22 16:50 UTC, yoshuawuyts commented on index.js
>    var archive = archiveOrKey.key ? archiveOrKey : createArchive(archiveOrKey)
believe we talked about this on IRC but not sure if we had a conclusive answer

2016-12-22 16:52 UTC, yoshuawuyts commented on index.js
> +  var feed = (archive.content) ? archive.content : archive
iirc `hyperhealth` does nothing in that case - e.g. `archive.content` is needed for https://github.com/karissa/hyperhealth/blob/master/index.js#L36-L37 - what should the value of `.content` be?

2016-12-22 16:54 UTC, joehand commented on index.js
> +  var feed = (archive.content) ? archive.content : archive
It doesn't do anything while [content isn't populated](https://github.com/karissa/hyperhealth/blob/master/index.js#L16). But once content [gets populated after the open](https://github.com/karissa/hyperhealth/blob/master/index.js#L9) (when a connection succeeds and metadata is fetched) then it starts to return the health.

2016-12-22 17:01 UTC, joehand commented on index.js
>    var archive = archiveOrKey.key ? archiveOrKey : createArchive(archiveOrKey)
You can use something [like this](https://github.com/mafintosh/hypercore-archiver/blob/master/index.js#L206). But there may be a more straightforward implementation I can try but need to go get ☕️ first :).

2016-12-22 17:05 UTC, yoshuawuyts commented on index.js
>    var archive = archiveOrKey.key ? archiveOrKey : createArchive(archiveOrKey)
as discussed on IRC a generic package might be neat to have to deal with this :D

2016-12-22 17:06 UTC, yoshuawuyts commented on index.js
>    archive.open(function () {
not sure, my knowledge of `hyperdrive` is limited - the logic is the same as before tho so I'd rather not deal with changing it in this patch hmm

2016-12-22 17:07 UTC, yoshuawuyts commented
updated!

2017-03-16 21:59 UTC, joehand commented
Done in #5. Made node API a bit easier in that PR =).

2017-03-16 21:59 UTC, closed without merging